# Generated by Django 2.1.5 on 2019-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0003_brand_department_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
