# Generated by Django 2.1.5 on 2019-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0004_auto_20190107_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bprice',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
