# Generated by Django 2.1.5 on 2019-01-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0008_systemmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(blank=True, default='1970-01-01'),
            preserve_default=False,
        ),
    ]
