# Generated by Django 2.1.5 on 2019-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0009_bookinfo_bpub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(null=True),
        ),
    ]
